version: "2.0"    # https://docs.docker.com/compose/compose-file/compose-file-v2/#context
services:

  shell:
    build: ./shell
    image: shell-ubuntu:18.04

  git:
    build: ./git
    image: git-ubuntu:18.04
    depends_on:
      - shell
    
  emacs:
    build: ./emacs
    image: emacs-ubuntu:18.04
    depends_on:
      - shell
      - git

  spacemacs:
    build: ./spacemacs
    image: spacemacs-ubuntu:18.04
    depends_on:
      - shell
      - git
      - emacs
    ports:
      - "50001:50001"
