FROM ubuntu:18.04
LABEL author='Jongho Kim'

# See: https://docs.docker.com/engine/reference/builder/
# FROM
# RUN
# CMD
# ENTRYPOINT
# LABEL
# EXPOSE
# ENV
# ARG
# ADD
# COPY
# VOLUME
# USER
# WORKDIR
# ONBUILD
# STOPSIGNAL
# HEALTHCHECK
# SHELL



#
ENV TERM=xterm-256color

# Emacs
#ENV emacs='emacs -nw'
RUN echo "alias emacs='emacs -nw'" >> ~/.bashrc
